#!/usr/bin/env bash

if [ $1 == "disable" ]; then

  # Launch Agents
  find "/Library/LaunchAgents/" -name "com.adobe.*.plist" -exec mv {} {}.bak \;
  find "$HOME/Library/LaunchAgents/" -name "com.adobe.*.plist" -exec mv {} {}.bak \;

  # Launch Daemons
  find "/Library/LaunchDaemons/" -name "com.adobe.*.plist" -exec mv {} {}.bak \;

elif [ $1 == "enable" ]; then

  echo "Not implemented! Why would you want to enable Adobe crapware??!?"
  echo "(seriously, this should be implemented in case the stuff is eventually needed)"

fi
