#!/usr/bin/env bash

# Arguments validity check
if [[ $# -ne 2 ]]; then
  echo "Usage: throttle [port-number] [KB/s]"
  exit 1
fi

# Store arguments
PORT=$1
KBPS=$2

# Throttle using the built-in traffic shaper
echo "NOT IMPLEMENTED! MUST USE dnctl ON YOSEMITE+!"
# dnctl pipe 1 config bw ${KBPS}KByte/s
# TODO! This should be implemented using dnctl on Yosemite+

echo "Throttling port $PORT at $KBPS KB/s."
echo "Press ENTER to stop throttling..."
read

# Stop throttling
# TODO!
